### ISSUE TITLE
`[` in mapping keys causes YAML_LOAD_ERR_BAD_MAP_ELEMENT

### ISSUE THREAD

**Issue by ferki** [ingydotnet/yaml-pm#209]
I've tried using YAML-1.26 to parse report files written by Puppet (AFAIK using `libyaml` behind the scenes), but I got `YAML_LOAD_ERR_BAD_MAP_ELEMENT` for content similar to the following snippet:

```yaml
resource_statuses:
  File[/path/to/file]: !ruby/object:Puppet::Resource::Status
    title: "/path/to/file"
```

It seems like the problem is with using `File[/path/to/file]` as key. Some quick cross-checking shows that the same would work when using YAML::XS-0.74 (due to `libyaml`), or when it is between single quotes (`'File[/path/to/file]'`).

Based on my quick initial debugging, it seems like it ends up parsed by `_parse_inline_simple` where the regular expression would only extract `File` due to the lookahead part matching the following `[`.

Is it possible to fix this without interfering too much with the flow sequence indicator, which is also `[`?

I'm happy to send a PR, but I probably would need a hint to push me in the right direction :)
