### ISSUE TITLE
Patch for loading modules. [rt.cpan.org #18979]

### ISSUE THREAD

**Issue by ingydotnet** [ingydotnet/yaml-pm#61]
https://rt.cpan.org/Ticket/Display.html?id=18979

```
When loading serialized modules, YAML fails to load the corresponding code. 



jesper@ubuntulap:~$ cat yamltest
--- !perl/DateTime
formatter: ~
local_c:
  day: 29
  day_of_quarter: 29
  day_of_week: 6
  day_of_year: 119
  hour: 12
  minute: 55
  month: 4
  quarter: 2
  second: 10
  year: 2006
local_rd_days: 732430
local_rd_secs: 46510
locale: !perl/DateTime::Locale::en_US
  default_date_format_length: medium
  default_time_format_length: medium
  en_complete_name: English United States
  en_language: English
  en_territory: United States
  id: en_US
  native_complete_name: English United States
  native_language: English
  native_territory: United States
offset_modifier: 0
rd_nanosecs: 0
tz: !perl/DateTime::TimeZone::UTC
  name: UTC
utc_rd_days: 732430
utc_rd_secs: 46510
utc_year: 2007

jesper@ubuntulap:~$ perl -MYAML -e'my $dt = YAML::LoadFile("yamltest");
print $dt->ymd() . "\n";'
Can't locate object method "ymd" via package "DateTime" at -e line 1.
jesper@ubuntulap:~$
```
